INSERT INTO `countries` (`country_name`, `country_code`, `zone`) VALUES
( 'Ireland, Republic Of\n', 'IE\n', 6),
( 'United Kingdom\n', 'GB\n', 4),
( 'United States Of America\n', 'US\n', 5),
( 'Australia\n', 'AU\n', 6),
( 'Canada\n', 'CA\n', 5),
( 'New Zealand\n', 'NZ\n', 6),
( 'Afghanistan\n', 'AF\n', 7),
( 'Albania\n', 'AL\n', 8),
( 'Algeria\n', 'DZ\n', 8),
( 'American Samoa\n', 'AS\n', 8),
( 'Andorra\n', 'AD\n', 8),
( 'Angola\n', 'AO\n', 8),
( 'Anguilla\n', 'AI\n', 8),
( 'Antigua\n', 'AG\n', 8),
( 'Argentina\n', 'AR\n', 8),
( 'Armenia\n', 'AM\n', 8),
( 'Aruba\n', 'AW\n', 8),
( 'Austria\n', 'AT\n', 6),
( 'Azerbaijan\n', 'AZ\n', 6),
( 'Bahamas\n', 'BS\n', 8),
( 'Bahrain\n', 'BH\n', 1),
( 'Bangladesh\n', 'BD\n', 3),
( 'Barbados\n', 'BB\n', 8),
( 'Belarus\n', 'BY\n', 8),
( 'Belgium\n', 'BE\n', 4),
( 'Belize\n', 'BZ\n', 8),
( 'Benin\n', 'BJ\n', 8),
( 'Bermuda\n', 'BM\n', 8),
( 'Bhutan\n', 'BT\n', 8),
( 'Bolivia\n', 'BO\n', 8),
( 'Bonaire\n', 'XB\n', 8),
( 'Bosnia and Herzegovina\n', 'BA\n', 6),
( 'Botswana\n', 'BW\n', 8),
( 'Brazil\n', 'BR\n', 8),
( 'Brunei\n', 'BN\n', 6),
( 'Bulgaria\n', 'BG\n', 6),
( 'Burkina Faso\n', 'BF\n', 8),
( 'Burundi\n', 'BI\n', 8),
( 'Cambodia\n', 'KH\n', 8),
( 'Cameroon\n', 'CM\n', 8),
( 'Canary Islands, The\n', 'IC\n', 8),
( 'Cape Verde\n', 'CV\n', 8),
( 'Cayman Islands\n', 'KY\n', 8),
( 'Central African Republic\n', 'CF\n', 8),
( 'Chad\n', 'TD\n', 8),
( 'Chile\n', 'CL\n', 8),
( 'China, People''s Republic\n', 'CN\n', 5),
( 'Colombia\n', 'CO\n', 8),
( 'Comoros\n', 'KM\n', 8),
( 'Congo\n', 'CG\n', 8),
( 'Congo, The Democratic Re\n', 'CD\n', 8),
( 'Cook Islands\n', 'CK\n', 8),
( 'Costa Rica\n', 'CR\n', 8),
( 'Cote d''Ivoire\n', 'CI\n', 8),
( 'Croatia\n', 'HR\n', 6),
( 'Cuba\n', 'CU\n', 8),
( 'Curacao\n', 'XC\n', 8),
( 'Cyprus\n', 'CY\n', 3),
( 'Czech Republic, The\n', 'CZ\n', 6),
( 'Denmark\n', 'DK\n', 4),
( 'Djibouti\n', 'DJ\n', 8),
( 'Dominica\n', 'DM\n', 8),
( 'Dominican Republic\n', 'DO\n', 8),
( 'East Timor\n', 'TP\n', 8),
( 'Ecuador\n', 'EC\n', 8),
( 'Egypt\n', 'EG\n', 3),
( 'El Salvador\n', 'SV\n', 8),
( 'Eritrea\n', 'ER\n', 8),
( 'Estonia\n', 'EE\n', 8),
( 'Ethiopia\n', 'ET\n', 8),
( 'Falkland Islands\n', 'FK\n', 8),
( 'Faroe Islands\n', 'FO\n', 8),
( 'Fiji\n', 'FJ\n', 8),
( 'Finland\n', 'FI\n', 6),
( 'France\n', 'FR\n', 4),
( 'French Guyana\n', 'GF\n', 8),
( 'Gabon\n', 'GA\n', 8),
( 'Gambia\n', 'GM\n', 8),
( 'Georgia\n', 'GE\n', 8),
( 'Germany\n', 'DE\n', 4),
( 'Ghana\n', 'GH\n', 8),
( 'Gibraltar\n', 'GI\n', 8),
( 'Greece\n', 'GR\n', 6),
( 'Greenland\n', 'GL\n', 8),
( 'Grenada\n', 'GD\n', 8),
( 'Guadeloupe\n', 'GP\n', 8),
( 'Guam\n', 'GU\n', 8),
( 'Guatemala\n', 'GT\n', 8),
( 'Guernsey\n', 'GG\n', 6),
( 'Guinea Republic\n', 'GN\n', 8),
( 'Guinea-Bissau\n', 'GW\n', 8),
( 'Guinea-Equatorial\n', 'GQ\n', 8),
( 'Guyana (British)\n', 'GY\n', 8),
( 'Haiti\n', 'HT\n', 8),
( 'Honduras\n', 'HN\n', 8),
( 'Hong Kong\n', 'HK\n', 5),
( 'Hungary\n', 'HU\n', 6),
( 'Iceland\n', 'IS\n', 8),
( 'India\n', 'IN\n', 3),
( 'Indonesia\n', 'ID\n', 6),
( 'Iran (Islamic Republic of)\n', 'IR\n', 2),
( 'Iraq\n', 'IQ\n', 7),
( 'Israel\n', 'IL\n', 8),
( 'Italy\n', 'IT\n', 4),
( 'Jamaica\n', 'JM\n', 8),
( 'Japan\n', 'JP\n', 6),
( 'Jersey\n', 'JE\n', 6),
( 'Jordan\n', 'JO\n', 2),
( 'Kazakhstan\n', 'KZ\n', 6),
( 'Kenya\n', 'KE\n', 8),
( 'Kiribati\n', 'KI\n', 8),
( 'Korea, Republic Of\n', 'KR\n', 6),
( 'Korea, The D.P.R of\n', 'KP\n', 8),
( 'Kosovo\n', 'KV\n', 8),
( 'Kuwait\n', 'KW\n', 0),
( 'Kyrgyzstan\n', 'KG\n', 8),
( 'Lao People''s Democratic Republic\n', 'LA\n', 8),
( 'Latvia\n', 'LV\n', 8),
( 'Lebanon\n', 'LB\n', 2),
( 'Lesotho\n', 'LS\n', 8),
( 'Liberia\n', 'LR\n', 8),
( 'Libya\n', 'LY\n', 8),
( 'Liechtenstein\n', 'LI\n', 6),
( 'Lithuania\n', 'LT\n', 8),
( 'Luxembourg\n', 'LU\n', 4),
( 'Macau\n', 'MO\n', 8),
( 'Macedonia, Republic of\n', 'MK\n', 8),
( 'Madagascar\n', 'MG\n', 8),
( 'Malawi\n', 'MW\n', 8),
( 'Malaysia\n', 'MY\n', 4),
( 'Maldives\n', 'MV\n', 8),
( 'Mali\n', 'ML\n', 8),
( 'Malta\n', 'MT\n', 6),
( 'Marshall Islands\n', 'MH\n', 8),
( 'Martinique\n', 'MQ\n', 8),
( 'Mauritania\n', 'MR\n', 8),
( 'Mauritius\n', 'MU\n', 8),
( 'Mayotte\n', 'YT\n', 8),
( 'Mexico\n', 'MX\n', 8),
( 'Micronesia, Federated States of\n', 'FM\n', 8),
( 'Moldova, Republic Of\n', 'MD\n', 8),
( 'Monaco\n', 'MC\n', 8),
( 'Mongolia\n', 'MN\n', 8),
( 'Montenegro, Republic of\n', 'ME\n', 8),
( 'Montserrat\n', 'MS\n', 8),
( 'Morocco\n', 'MA\n', 8),
( 'Mozambique\n', 'MZ\n', 8),
( 'Myanmar\n', 'MM\n', 8),
( 'Namibia\n', 'NA\n', 8),
( 'Nauru, Republic Of\n', 'NR\n', 8),
( 'Nepal\n', 'NP\n', 6),
( 'Netherlands Antilles\n', 'AN\n', 8),
( 'Netherlands, The\n', 'NL\n', 4),
( 'Nevis\n', 'XN\n', 8),
( 'New Caledonia\n', 'NC\n', 8),
( 'Nicaragua\n', 'NI\n', 8),
( 'Niger\n', 'NE\n', 8),
( 'Nigeria\n', 'NG\n', 8),
( 'Niue\n', 'NU\n', 8),
( 'Norway\n', 'NO\n', 6),
( 'Oman\n', 'OM\n', 1),
( 'Pakistan\n', 'PK\n', 3),
( 'Palau\n', 'PW\n', 8),
( 'Panama\n', 'PA\n', 8),
( 'Papua New Guinea\n', 'PG\n', 8),
( 'Paraguay\n', 'PY\n', 8),
( 'Peru\n', 'PE\n', 8),
( 'Philippines, The\n', 'PH\n', 6),
( 'Poland\n', 'PL\n', 6),
( 'Portugal\n', 'PT\n', 6),
( 'Puerto Rico\n', 'PR\n', 8),
( 'Qatar\n', 'QA\n', 1),
( 'Reunion, Island Of\n', 'RE\n', 8),
( 'Romania\n', 'RO\n', 6),
( 'Russian Federation, The\n', 'RU\n', 6),
( 'Rwanda\n', 'RW\n', 8),
( 'Saipan\n', 'MP\n', 8),
( 'Samoa\n', 'WS\n', 8),
( 'San Marino\n', 'SM\n', 8),
( 'Sao Tome and Principe\n', 'ST\n', 8),
( 'Saudi Arabia\n', 'SA\n', 2),
( 'Senegal\n', 'SN\n', 8),
( 'Serbia, Republic of\n', 'RS\n', 8),
( 'Seychelles\n', 'SC\n', 8),
( 'Sierra Leone\n', 'SL\n', 8),
( 'Singapore\n', 'SG\n', 6),
( 'Slovakia\n', 'SK\n', 8),
( 'Slovenia\n', 'SI\n', 8),
( 'Solomon Islands\n', 'SB\n', 8),
( 'Somalia\n', 'SO\n', 8),
( 'Somaliland, Rep of (North Somali\n', 'XS\n', 8),
( 'South Africa\n', 'ZA\n', 8),
( 'Spain\n', 'ES\n', 6),
( 'Sri Lanka\n', 'LK\n', 3),
( 'St. Barthelemy\n', 'XY\n', 8),
( 'St. Eustatius\n', 'XE\n', 8),
( 'St. Kitts\n', 'KN\n', 8),
( 'St. Lucia\n', 'LC\n', 8),
( 'St. Maarten\n', 'XM\n', 8),
( 'St. Vincent\n', 'VC\n', 8),
( 'Sudan\n', 'SD\n', 6),
( 'Suriname\n', 'SR\n', 8),
( 'Swaziland\n', 'SZ\n', 8),
( 'Sweden\n', 'SE\n', 4),
( 'Switzerland\n', 'CH\n', 4),
( 'Syria\n', 'SY\n', 2),
( 'Tahiti\n', 'PF\n', 8),
( 'Taiwan\n', 'TW\n', 6),
( 'Tajikistan\n', 'TJ\n', 8),
( 'Tanzania\n', 'TZ\n', 8),
( 'Thailand\n', 'TH\n', 6),
( 'Togo\n', 'TG\n', 8),
( 'Tonga\n', 'TO\n', 8),
( 'Trinidad and Tobago\n', 'TT\n', 8),
( 'Tunisia\n', 'TN\n', 8),
( 'Turkey\n', 'TR\n', 6),
( 'Turkmenistan\n', 'TM\n', 6),
( 'Turks and Caicos Islands\n', 'TC\n', 8),
( 'Tuvalu\n', 'TV\n', 8),
( 'Uganda\n', 'UG\n', 8),
( 'Ukraine\n', 'UA\n', 8),
( 'United Arab Emirates\n', 'AE\n', 1),
( 'Uruguay\n', 'UY\n', 8),
( 'Uzbekistan\n', 'UZ\n', 8),
( 'Vanuatu\n', 'VU\n', 8),
( 'Venezuela\n', 'VE\n', 8),
( 'Vietnam\n', 'VN\n', 8),
( 'Virgin Islands (British)\n', 'VG\n', 8),
( 'Virgin Islands (US)\n', 'VI\n', 8),
( 'Yemen, Republic of\n', 'YE\n', 3),
( 'Zambia\n', 'ZM\n', 8),
( 'Zimbabwe\n', 'ZW\n', 8);
