class Addcountries < ActiveRecord::Migration
  def change
    Country.create(:zone=>1,:country_code=>"AD",:country_name=>"Andorra")
    Country.create(:zone=>2,:country_code=>"AE",:country_name=>"United Arab Emirates")
    Country.create(:zone=>3,:country_code=>"AF",:country_name=>"Afghanistan")
    Country.create(:zone=>4,:country_code=>"AG",:country_name=>"Antigua and Barbuda")
    Country.create(:zone=>5,:country_code=>"AI",:country_name=>"Anguilla")
    Country.create(:zone=>6,:country_code=>"AL",:country_name=>"Albania")
    Country.create(:zone=>7,:country_code=>"AM",:country_name=>"Armenia")
    Country.create(:zone=>8,:country_code=>"AO",:country_name=>"Angola")
    Country.create(:zone=>9,:country_code=>"AQ",:country_name=>"Antarctica")
    Country.create(:zone=>10,:country_code=>"AR",:country_name=>"Argentina")
    Country.create(:zone=>11,:country_code=>"AS",:country_name=>"American Samoa")
    Country.create(:zone=>12,:country_code=>"AT",:country_name=>"Austria")
    Country.create(:zone=>13,:country_code=>"AU",:country_name=>"Australia")
    Country.create(:zone=>14,:country_code=>"AW",:country_name=>"Aruba")
    Country.create(:zone=>15,:country_code=>"AX",:country_name=>"Aland Islands")
    Country.create(:zone=>16,:country_code=>"AZ",:country_name=>"Azerbaijan")
    Country.create(:zone=>17,:country_code=>"BA",:country_name=>"Bosnia and Herzegovina")
    Country.create(:zone=>18,:country_code=>"BB",:country_name=>"Barbados")
    Country.create(:zone=>19,:country_code=>"BD",:country_name=>"Bangladesh")
    Country.create(:zone=>20,:country_code=>"BE",:country_name=>"Belgium")
    Country.create(:zone=>21,:country_code=>"BF",:country_name=>"Burkina Faso")
    Country.create(:zone=>22,:country_code=>"BG",:country_name=>"Bulgaria")
    Country.create(:zone=>23,:country_code=>"BH",:country_name=>"Bahrain")
    Country.create(:zone=>24,:country_code=>"BI",:country_name=>"Burundi")
    Country.create(:zone=>25,:country_code=>"BJ",:country_name=>"Benin")
    Country.create(:zone=>26,:country_code=>"BL",:country_name=>"Saint Barthelemy")
    Country.create(:zone=>27,:country_code=>"BM",:country_name=>"Bermuda")
    Country.create(:zone=>28,:country_code=>"BN",:country_name=>"Brunei")
    Country.create(:zone=>29,:country_code=>"BO",:country_name=>"Bolivia")
    Country.create(:zone=>30,:country_code=>"BQ",:country_name=>"Bonaire, Saint Eustatius and Saba ")
    Country.create(:zone=>31,:country_code=>"BR",:country_name=>"Brazil")
    Country.create(:zone=>32,:country_code=>"BS",:country_name=>"Bahamas")
    Country.create(:zone=>33,:country_code=>"BT",:country_name=>"Bhutan")
    Country.create(:zone=>34,:country_code=>"BV",:country_name=>"Bouvet Island")
    Country.create(:zone=>35,:country_code=>"BW",:country_name=>"Botswana")
    Country.create(:zone=>36,:country_code=>"BY",:country_name=>"Belarus")
    Country.create(:zone=>37,:country_code=>"BZ",:country_name=>"Belize")
    Country.create(:zone=>38,:country_code=>"CA",:country_name=>"Canada")
    Country.create(:zone=>39,:country_code=>"CC",:country_name=>"Cocos Islands")
    Country.create(:zone=>40,:country_code=>"CD",:country_name=>"Democratic Republic of the Congo")
    Country.create(:zone=>41,:country_code=>"CF",:country_name=>"Central African Republic")
    Country.create(:zone=>42,:country_code=>"CG",:country_name=>"Republic of the Congo")
    Country.create(:zone=>43,:country_code=>"CH",:country_name=>"Switzerland")
    Country.create(:zone=>44,:country_code=>"CI",:country_name=>"Ivory Coast")
    Country.create(:zone=>45,:country_code=>"CK",:country_name=>"Cook Islands")
    Country.create(:zone=>46,:country_code=>"CL",:country_name=>"Chile")
    Country.create(:zone=>47,:country_code=>"CM",:country_name=>"Cameroon")
    Country.create(:zone=>48,:country_code=>"CN",:country_name=>"China")
    Country.create(:zone=>49,:country_code=>"CO",:country_name=>"Colombia")
    Country.create(:zone=>50,:country_code=>"CR",:country_name=>"Costa Rica")
    Country.create(:zone=>51,:country_code=>"CU",:country_name=>"Cuba")
    Country.create(:zone=>52,:country_code=>"CV",:country_name=>"Cape Verde")
    Country.create(:zone=>53,:country_code=>"CW",:country_name=>"Curacao")
    Country.create(:zone=>54,:country_code=>"CX",:country_name=>"Christmas Island")
    Country.create(:zone=>55,:country_code=>"CY",:country_name=>"Cyprus")
    Country.create(:zone=>56,:country_code=>"CZ",:country_name=>"Czech Republic")
    Country.create(:zone=>57,:country_code=>"DE",:country_name=>"Germany")
    Country.create(:zone=>58,:country_code=>"DJ",:country_name=>"Djibouti")
    Country.create(:zone=>59,:country_code=>"DK",:country_name=>"Denmark")
    Country.create(:zone=>60,:country_code=>"DM",:country_name=>"Dominica")
    Country.create(:zone=>61,:country_code=>"DO",:country_name=>"Dominican Republic")
    Country.create(:zone=>62,:country_code=>"DZ",:country_name=>"Algeria")
    Country.create(:zone=>63,:country_code=>"EC",:country_name=>"Ecuador")
    Country.create(:zone=>64,:country_code=>"EE",:country_name=>"Estonia")
    Country.create(:zone=>65,:country_code=>"EG",:country_name=>"Egypt")
    Country.create(:zone=>66,:country_code=>"EH",:country_name=>"Western Sahara")
    Country.create(:zone=>67,:country_code=>"ER",:country_name=>"Eritrea")
    Country.create(:zone=>68,:country_code=>"ES",:country_name=>"Spain")
    Country.create(:zone=>69,:country_code=>"ET",:country_name=>"Ethiopia")
    Country.create(:zone=>70,:country_code=>"FI",:country_name=>"Finland")
    Country.create(:zone=>71,:country_code=>"FJ",:country_name=>"Fiji")
    Country.create(:zone=>72,:country_code=>"FK",:country_name=>"Falkland Islands")
    Country.create(:zone=>73,:country_code=>"FM",:country_name=>"Micronesia")
    Country.create(:zone=>74,:country_code=>"FO",:country_name=>"Faroe Islands")
    Country.create(:zone=>75,:country_code=>"FR",:country_name=>"France")
    Country.create(:zone=>76,:country_code=>"GA",:country_name=>"Gabon")
    Country.create(:zone=>77,:country_code=>"GB",:country_name=>"United Kingdom")
    Country.create(:zone=>78,:country_code=>"GD",:country_name=>"Grenada")
    Country.create(:zone=>79,:country_code=>"GE",:country_name=>"Georgia")
    Country.create(:zone=>80,:country_code=>"GF",:country_name=>"French Guiana")
    Country.create(:zone=>81,:country_code=>"GG",:country_name=>"Guernsey")
    Country.create(:zone=>82,:country_code=>"GH",:country_name=>"Ghana")
    Country.create(:zone=>83,:country_code=>"GI",:country_name=>"Gibraltar")
    Country.create(:zone=>84,:country_code=>"GL",:country_name=>"Greenland")
    Country.create(:zone=>85,:country_code=>"GM",:country_name=>"Gambia")
    Country.create(:zone=>86,:country_code=>"GN",:country_name=>"Guinea")
    Country.create(:zone=>87,:country_code=>"GP",:country_name=>"Guadeloupe")
    Country.create(:zone=>88,:country_code=>"GQ",:country_name=>"Equatorial Guinea")
    Country.create(:zone=>89,:country_code=>"GR",:country_name=>"Greece")
    Country.create(:zone=>90,:country_code=>"GS",:country_name=>"South Georgia and the South Sandwich Islands")
    Country.create(:zone=>91,:country_code=>"GT",:country_name=>"Guatemala")
    Country.create(:zone=>92,:country_code=>"GU",:country_name=>"Guam")
    Country.create(:zone=>93,:country_code=>"GW",:country_name=>"Guinea-Bissau")
    Country.create(:zone=>94,:country_code=>"GY",:country_name=>"Guyana")
    Country.create(:zone=>95,:country_code=>"HK",:country_name=>"Hong Kong")
    Country.create(:zone=>96,:country_code=>"HM",:country_name=>"Heard Island and McDonald Islands")
    Country.create(:zone=>97,:country_code=>"HN",:country_name=>"Honduras")
    Country.create(:zone=>98,:country_code=>"HR",:country_name=>"Croatia")
    Country.create(:zone=>99,:country_code=>"HT",:country_name=>"Haiti")
    Country.create(:zone=>100,:country_code=>"HU",:country_name=>"Hungary")
    Country.create(:zone=>101,:country_code=>"ID",:country_name=>"Indonesia")
    Country.create(:zone=>102,:country_code=>"IE",:country_name=>"Ireland")
    Country.create(:zone=>103,:country_code=>"IL",:country_name=>"Israel")
    Country.create(:zone=>104,:country_code=>"IM",:country_name=>"Isle of Man")
    Country.create(:zone=>105,:country_code=>"IN",:country_name=>"India")
    Country.create(:zone=>106,:country_code=>"IO",:country_name=>"British Indian Ocean Territory")
    Country.create(:zone=>107,:country_code=>"IQ",:country_name=>"Iraq")
    Country.create(:zone=>108,:country_code=>"IR",:country_name=>"Iran")
    Country.create(:zone=>109,:country_code=>"IS",:country_name=>"Iceland")
    Country.create(:zone=>110,:country_code=>"IT",:country_name=>"Italy")
    Country.create(:zone=>111,:country_code=>"JE",:country_name=>"Jersey")
    Country.create(:zone=>112,:country_code=>"JM",:country_name=>"Jamaica")
    Country.create(:zone=>113,:country_code=>"JO",:country_name=>"Jordan")
    Country.create(:zone=>114,:country_code=>"JP",:country_name=>"Japan")
    Country.create(:zone=>115,:country_code=>"KE",:country_name=>"Kenya")
    Country.create(:zone=>116,:country_code=>"KG",:country_name=>"Kyrgyzstan")
    Country.create(:zone=>117,:country_code=>"KH",:country_name=>"Cambodia")
    Country.create(:zone=>118,:country_code=>"KI",:country_name=>"Kiribati")
    Country.create(:zone=>119,:country_code=>"KM",:country_name=>"Comoros")
    Country.create(:zone=>120,:country_code=>"KN",:country_name=>"Saint Kitts and Nevis")
    Country.create(:zone=>121,:country_code=>"KP",:country_name=>"North Korea")
    Country.create(:zone=>122,:country_code=>"KR",:country_name=>"South Korea")
    Country.create(:zone=>123,:country_code=>"XK",:country_name=>"Kosovo")
    Country.create(:zone=>124,:country_code=>"KW",:country_name=>"Kuwait")
    Country.create(:zone=>125,:country_code=>"KY",:country_name=>"Cayman Islands")
    Country.create(:zone=>126,:country_code=>"KZ",:country_name=>"Kazakhstan")
    Country.create(:zone=>127,:country_code=>"LA",:country_name=>"Laos")
    Country.create(:zone=>128,:country_code=>"LB",:country_name=>"Lebanon")
    Country.create(:zone=>129,:country_code=>"LC",:country_name=>"Saint Lucia")
    Country.create(:zone=>130,:country_code=>"LI",:country_name=>"Liechtenstein")
    Country.create(:zone=>131,:country_code=>"LK",:country_name=>"Sri Lanka")
    Country.create(:zone=>132,:country_code=>"LR",:country_name=>"Liberia")
    Country.create(:zone=>133,:country_code=>"LS",:country_name=>"Lesotho")
    Country.create(:zone=>134,:country_code=>"LT",:country_name=>"Lithuania")
    Country.create(:zone=>135,:country_code=>"LU",:country_name=>"Luxembourg")
    Country.create(:zone=>136,:country_code=>"LV",:country_name=>"Latvia")
    Country.create(:zone=>137,:country_code=>"LY",:country_name=>"Libya")
    Country.create(:zone=>138,:country_code=>"MA",:country_name=>"Morocco")
    Country.create(:zone=>139,:country_code=>"MC",:country_name=>"Monaco")
    Country.create(:zone=>140,:country_code=>"MD",:country_name=>"Moldova")
    Country.create(:zone=>141,:country_code=>"ME",:country_name=>"Montenegro")
    Country.create(:zone=>142,:country_code=>"MF",:country_name=>"Saint Martin")
    Country.create(:zone=>143,:country_code=>"MG",:country_name=>"Madagascar")
    Country.create(:zone=>144,:country_code=>"MH",:country_name=>"Marshall Islands")
    Country.create(:zone=>145,:country_code=>"MK",:country_name=>"Macedonia")
    Country.create(:zone=>146,:country_code=>"ML",:country_name=>"Mali")
    Country.create(:zone=>147,:country_code=>"MM",:country_name=>"Myanmar")
    Country.create(:zone=>148,:country_code=>"MN",:country_name=>"Mongolia")
    Country.create(:zone=>149,:country_code=>"MO",:country_name=>"Macao")
    Country.create(:zone=>150,:country_code=>"MP",:country_name=>"Northern Mariana Islands")
    Country.create(:zone=>151,:country_code=>"MQ",:country_name=>"Martinique")
    Country.create(:zone=>152,:country_code=>"MR",:country_name=>"Mauritania")
    Country.create(:zone=>153,:country_code=>"MS",:country_name=>"Montserrat")
    Country.create(:zone=>154,:country_code=>"MT",:country_name=>"Malta")
    Country.create(:zone=>155,:country_code=>"MU",:country_name=>"Mauritius")
    Country.create(:zone=>156,:country_code=>"MV",:country_name=>"Maldives")
    Country.create(:zone=>157,:country_code=>"MW",:country_name=>"Malawi")
    Country.create(:zone=>158,:country_code=>"MX",:country_name=>"Mexico")
    Country.create(:zone=>159,:country_code=>"MY",:country_name=>"Malaysia")
    Country.create(:zone=>160,:country_code=>"MZ",:country_name=>"Mozambique")
    Country.create(:zone=>161,:country_code=>"NA",:country_name=>"Namibia")
    Country.create(:zone=>162,:country_code=>"NC",:country_name=>"New Caledonia")
    Country.create(:zone=>163,:country_code=>"NE",:country_name=>"Niger")
    Country.create(:zone=>164,:country_code=>"NF",:country_name=>"Norfolk Island")
    Country.create(:zone=>165,:country_code=>"NG",:country_name=>"Nigeria")
    Country.create(:zone=>166,:country_code=>"NI",:country_name=>"Nicaragua")
    Country.create(:zone=>167,:country_code=>"NL",:country_name=>"Netherlands")
    Country.create(:zone=>168,:country_code=>"NO",:country_name=>"Norway")
    Country.create(:zone=>169,:country_code=>"NP",:country_name=>"Nepal")
    Country.create(:zone=>170,:country_code=>"NR",:country_name=>"Nauru")
    Country.create(:zone=>171,:country_code=>"NU",:country_name=>"Niue")
    Country.create(:zone=>172,:country_code=>"NZ",:country_name=>"New Zealand")
    Country.create(:zone=>173,:country_code=>"OM",:country_name=>"Oman")
    Country.create(:zone=>174,:country_code=>"PA",:country_name=>"Panama")
    Country.create(:zone=>175,:country_code=>"PE",:country_name=>"Peru")
    Country.create(:zone=>176,:country_code=>"PF",:country_name=>"French Polynesia")
    Country.create(:zone=>177,:country_code=>"PG",:country_name=>"Papua New Guinea")
    Country.create(:zone=>178,:country_code=>"PH",:country_name=>"Philippines")
    Country.create(:zone=>179,:country_code=>"PK",:country_name=>"Pakistan")
    Country.create(:zone=>180,:country_code=>"PL",:country_name=>"Poland")
    Country.create(:zone=>181,:country_code=>"PM",:country_name=>"Saint Pierre and Miquelon")
    Country.create(:zone=>182,:country_code=>"PN",:country_name=>"Pitcairn")
    Country.create(:zone=>183,:country_code=>"PR",:country_name=>"Puerto Rico")
    Country.create(:zone=>184,:country_code=>"PS",:country_name=>"Palestinian Territory")
    Country.create(:zone=>185,:country_code=>"PT",:country_name=>"Portugal")
    Country.create(:zone=>186,:country_code=>"PW",:country_name=>"Palau")
    Country.create(:zone=>187,:country_code=>"PY",:country_name=>"Paraguay")
    Country.create(:zone=>188,:country_code=>"QA",:country_name=>"Qatar")
    Country.create(:zone=>189,:country_code=>"RE",:country_name=>"Reunion")
    Country.create(:zone=>190,:country_code=>"RO",:country_name=>"Romania")
    Country.create(:zone=>191,:country_code=>"RS",:country_name=>"Serbia")
    Country.create(:zone=>192,:country_code=>"RU",:country_name=>"Russia")
    Country.create(:zone=>193,:country_code=>"RW",:country_name=>"Rwanda")
    Country.create(:zone=>194,:country_code=>"SA",:country_name=>"Saudi Arabia")
    Country.create(:zone=>195,:country_code=>"SB",:country_name=>"Solomon Islands")
    Country.create(:zone=>196,:country_code=>"SC",:country_name=>"Seychelles")
    Country.create(:zone=>197,:country_code=>"SD",:country_name=>"Sudan")
    Country.create(:zone=>198,:country_code=>"SE",:country_name=>"Sweden")
    Country.create(:zone=>199,:country_code=>"SG",:country_name=>"Singapore")
    Country.create(:zone=>200,:country_code=>"SH",:country_name=>"Saint Helena")
    Country.create(:zone=>201,:country_code=>"SI",:country_name=>"Slovenia")
    Country.create(:zone=>202,:country_code=>"SJ",:country_name=>"Svalbard and Jan Mayen")
    Country.create(:zone=>203,:country_code=>"SK",:country_name=>"Slovakia")
    Country.create(:zone=>204,:country_code=>"SL",:country_name=>"Sierra Leone")
    Country.create(:zone=>205,:country_code=>"SM",:country_name=>"San Marino")
    Country.create(:zone=>206,:country_code=>"SN",:country_name=>"Senegal")
    Country.create(:zone=>207,:country_code=>"SO",:country_name=>"Somalia")
    Country.create(:zone=>208,:country_code=>"SR",:country_name=>"Suricountry_name")
    Country.create(:zone=>209,:country_code=>"ST",:country_name=>"Sao Tome and Principe")
    Country.create(:zone=>210,:country_code=>"SV",:country_name=>"El Salvador")
    Country.create(:zone=>211,:country_code=>"SX",:country_name=>"Sint Maarten")
    Country.create(:zone=>212,:country_code=>"SY",:country_name=>"Syria")
    Country.create(:zone=>213,:country_code=>"SZ",:country_name=>"Swaziland")
    Country.create(:zone=>214,:country_code=>"TC",:country_name=>"Turks and Caicos Islands")
    Country.create(:zone=>215,:country_code=>"TD",:country_name=>"Chad")
    Country.create(:zone=>216,:country_code=>"TF",:country_name=>"French Southern Territories")
    Country.create(:zone=>217,:country_code=>"TG",:country_name=>"Togo")
    Country.create(:zone=>218,:country_code=>"TH",:country_name=>"Thailand")
    Country.create(:zone=>219,:country_code=>"TJ",:country_name=>"Tajikistan")
    Country.create(:zone=>220,:country_code=>"TK",:country_name=>"Tokelau")
    Country.create(:zone=>221,:country_code=>"TL",:country_name=>"East Timor")
    Country.create(:zone=>222,:country_code=>"TM",:country_name=>"Turkmenistan")
    Country.create(:zone=>223,:country_code=>"TN",:country_name=>"Tunisia")
    Country.create(:zone=>224,:country_code=>"TO",:country_name=>"Tonga")
    Country.create(:zone=>225,:country_code=>"TR",:country_name=>"Turkey")
    Country.create(:zone=>226,:country_code=>"TT",:country_name=>"Trinidad and Tobago")
    Country.create(:zone=>227,:country_code=>"TV",:country_name=>"Tuvalu")
    Country.create(:zone=>228,:country_code=>"TW",:country_name=>"Taiwan")
    Country.create(:zone=>229,:country_code=>"TZ",:country_name=>"Tanzania")
    Country.create(:zone=>230,:country_code=>"UA",:country_name=>"Ukraine")
    Country.create(:zone=>231,:country_code=>"UG",:country_name=>"Uganda")
    Country.create(:zone=>232,:country_code=>"UM",:country_name=>"United States Minor Outlying Islands")
    Country.create(:zone=>233,:country_code=>"US",:country_name=>"United States")
    Country.create(:zone=>234,:country_code=>"UY",:country_name=>"Uruguay")
    Country.create(:zone=>235,:country_code=>"UZ",:country_name=>"Uzbekistan")
    Country.create(:zone=>236,:country_code=>"VA",:country_name=>"Vatican")
    Country.create(:zone=>237,:country_code=>"VC",:country_name=>"Saint Vincent and the Grenadines")
    Country.create(:zone=>238,:country_code=>"VE",:country_name=>"Venezuela")
    Country.create(:zone=>239,:country_code=>"VG",:country_name=>"British Virgin Islands")
    Country.create(:zone=>240,:country_code=>"VI",:country_name=>"U.S. Virgin Islands")
    Country.create(:zone=>241,:country_code=>"VN",:country_name=>"Vietnam")
    Country.create(:zone=>242,:country_code=>"VU",:country_name=>"Vanuatu")
    Country.create(:zone=>243,:country_code=>"WF",:country_name=>"Wallis and Futuna")
    Country.create(:zone=>244,:country_code=>"WS",:country_name=>"Samoa")
    Country.create(:zone=>245,:country_code=>"YE",:country_name=>"Yemen")
    Country.create(:zone=>246,:country_code=>"YT",:country_name=>"Mayotte")
    Country.create(:zone=>247,:country_code=>"ZA",:country_name=>"South Africa")
    Country.create(:zone=>248,:country_code=>"ZM",:country_name=>"Zambia")
    Country.create(:zone=>249,:country_code=>"ZW",:country_name=>"Zimbabwe")
    Country.create(:zone=>250,:country_code=>"CS",:country_name=>"Serbia and Montenegro")
    Country.create(:zone=>251,:country_code=>"AN",:country_name=>"Netherlands Antilles")
  end
end
